name: Build Modified APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Build APK
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug
        
    - name: Create APK ZIP artifact # 替代直接上传
      run: |
        mkdir artifact
        cp app/build/outputs/apk/debug/*.apk artifact/
        zip -r epubium-apk.zip artifact/
        
    - name: Upload APK ZIP
      uses: actions/upload-artifact@v4
      with:
        name: epubium-volume-mod-apk
        path: epubium-apk.zip
