name: EPUBium Volume Key Build (Java 11 Fixed)

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  setup_android_sdk:
    name: Setup Android SDK
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 使用JDK 11
      - name: Set up JDK 11 for SDK Tools
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Set Android Home
        run: |
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          
      - name: Download Android Tools
        run: |
          # 使用兼容JDK 11的最新工具版本
          TOOLS_VERSION="10406996"
          wget https://dl.google.com/android/repository/commandlinetools-linux-${TOOLS_VERSION}_latest.zip -O tools.zip
          unzip tools.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          rm tools.zip
        
      # 接受所有必需的Android许可证
      - name: Accept Android Licenses
        run: |
          mkdir -p $ANDROID_HOME/licenses
          echo -e "8933bad161af4178b1185d1f37dbf86a\nd56f5187479451a728f00fdead2e6e72" > $ANDROID_HOME/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c72" > $ANDROID_HOME/licenses/android-sdk-preview-license
          
      # 安装指定版本的SDK组件
      - name: Install SDK Components
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;29.0.3"

      # 输出SDK路径供后续使用
      - name: Export SDK Path
        id: export-sdk
        run: |
          echo "android-home=$ANDROID_HOME" >> $GITHUB_OUTPUT

  build_apk:
    name: Build APK
    needs: setup_android_sdk
    runs-on: ubuntu-22.04
    steps:
      # 为Gradle构建配置Java环境
      - name: Set up JDK for Gradle
        uses: actions/setup-java@v4
        with:
          java-version: '8' # Gradle 6.1.1需要Java 8
          distribution: 'temurin'
      
      - name: Checkout code
        uses: actions/checkout@v4
        
      # 配置SDK路径
      - name: Configure SDK Path
        run: |
          echo "sdk.dir=${{ needs.setup_android_sdk.outputs.android-home }}" > local.properties
          
      - name: Make Gradlew Executable
        run: chmod +x gradlew
          
      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace
        
      - name: Prepare APK Artifact
        run: |
          mkdir apk-artifact
          cp app/build/outputs/apk/debug/*.apk apk-artifact/
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: epubium-volume-mod-apk
          path: apk-artifact/
          
      # Java版本验证
      - name: Verify Java Versions
        run: |
          echo "=== SDK工具使用的Java版本 ==="
          ${{ needs.setup_android_sdk.outputs.android-home }}/cmdline-tools/latest/bin/sdkmanager --version
          
          echo "=== Gradle构建使用的Java版本 ==="
          java -version
          ./gradlew --version | grep "Java Version"
