name: Build Modified APK

on: [push] # 代码推送时自动构建

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Build APK
      run: |
        # 设置 Gradle 缓存
        export GRADLE_USER_HOME=${{ runner.temp }}/.gradle
        
        # 赋予执行权限
        chmod +x ./gradlew
        
        # 构建 APK
        ./gradlew assembleDebug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: modified-epubium-apk
        path: app/build/outputs/apk/debug/
