name: Android Build Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]  # 必须使用 JDK 17
        gradle: [8.0.2]  # 配套 JDK 17

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: amyu/setup-android@v4  # 升级到新版Action
        with:
          sdk-version: 34  # 指定Android 13平台
          cmdline-tools-version: "12.0"  # 已验证可用版本
          build-tools-version: "34.0.0"  # 验证可用版本
          ndk-version: 25.2.9519653  # 推荐最新稳定版
          cmake-version: 3.25.1  # 推荐最新稳定版

      - name: Configure SDK Mirror (China)
        run: |
          mkdir -p ~/.android
          echo "sdk.dir=/usr/local/lib/android/sdk" > ~/.android/sdk.cfg
          echo "sdkman.dir=/usr/local/lib/android/sdk" >> ~/.android/sdk.cfg
          echo "sdkman.mirror.url=https://mirrors.neusoft.edu.cn" >> ~/.android/sdk.cfg

      - name: Clean SDK Cache
        run: |
          rm -rf ~/.android/sdk/cmdline-tools
          rm -rf ~/.android/sdk/build-tools
          rm -rf ~/.android/sdk/platforms

      - name: Install SDK Components
        run: |
          sdkmanager --install "cmdline-tools;12.0" --verbose
          sdkmanager --install "build-tools;34.0.0" --verbose
          sdkmanager --install "platforms;android-34" --verbose
          sdkmanager --install "cmake;3.25.1" --verbose

      - name: Configure Project
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          echo "org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties

      - name: Build Release APK
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false"
        run: ./gradlew assembleRelease --stacktrace --info

      - name: Sign APK
        if: github.ref == 'refs/heads/main'
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release-APK
          path: |
            app/build/outputs/apk/release/*.apk
            build/reports/tests/test/*.html
            build/reports/gradle-logs/
