name: EPUBium Build with Volume Key Mod

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  setup_android_sdk:
    name: Setup Android SDK
    runs-on: ubuntu-22.04
    outputs:
      android-sdk-path: ${{ steps.setup.outputs.android-home }}
    steps:
      - name: Checkout minimal code
        uses: actions/checkout@v4
        with:
          path: sdk-setup
          fetch-depth: 1  # 只获取最新提交，加速下载
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 手动下载Android命令行工具
      - name: Download Android Tools
        run: |
          # 使用当前有效的版本号
          TOOLS_VERSION="10406996"
          wget https://dl.google.com/android/repository/commandlinetools-linux-${TOOLS_VERSION}_latest.zip -O tools.zip
          unzip tools.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          rm tools.zip
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
        
      - name: Accept licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          
      - name: Install essential packages
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33"
          
      - name: Export SDK path
        run: echo "android-home=$ANDROID_HOME" >> $GITHUB_OUTPUT

  build_apk:
    name: Build APK
    needs: setup_android_sdk
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout full code
        uses: actions/checkout@v4
        
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          
      - name: Configure SDK path
        run: |
          echo "sdk.dir=${{ needs.setup_android_sdk.outputs.android-sdk-path }}" > local.properties
          
      - name: Fix gradlew permissions
        run: chmod +x gradlew
          
      - name: Build APK
        run: ./gradlew assembleDebug
        env:
          ORG_GRADLE_PROJECT_mavenLocalRepo: ${{ github.workspace }}/.m2/repository
        
      - name: Prepare artifact
        run: |
          mkdir apk-artifact
          cp app/build/outputs/apk/debug/*.apk apk-artifact/
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: epubium-volume-mod-apk
          path: apk-artifact/
          
      # 附加调试信息
      - name: Collect debug info
        if: ${{ always() }}
        run: |
          echo "====== Android SDK Contents ======"
          ls -lR ${{ needs.setup_android_sdk.outputs.android-sdk-path }}
          echo "====== Gradle Version ======"
          ./gradlew --version
        shell: bash
